(()=>{const login=document.querySelector("#login-card"),content=document.querySelector("#creator-content"),loginForm=document.querySelector("#login-form"),loginStatus=document.querySelector("#login-status"),gameForm=document.querySelector("#game-form"),creatorStatus=document.querySelector("#creator-status"),list=document.querySelector("#admin-games"),signout=document.querySelector("#signout"),editDialog=document.querySelector("#edit-dialog"),editForm=document.querySelector("#edit-form");let token=sessionStorage.getItem("refs_token")||"",games=[];
async function auth(email,password){if(!configured())throw new Error("Connect the new Supabase project in config.js first.");const r=await fetch(`${CFG.supabaseUrl}/auth/v1/token?grant_type=password`,{method:"POST",headers:headers(),body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error_description||"Sign-in failed");return d.access_token}
loginForm.onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(loginForm));try{token=await auth(d.email,d.password);sessionStorage.setItem("refs_token",token);showCreator()}catch(err){loginStatus.className="status error";loginStatus.textContent=err.message}};
signout.onclick=()=>{sessionStorage.removeItem("refs_token");location.reload()};
async function showCreator(){login.hidden=true;content.hidden=false;signout.hidden=false;await load()}
async function load(){try{games=await rpc("get_admin_games",{},token);render()}catch(err){if(/jwt|sign|auth/i.test(err.message)){sessionStorage.removeItem("refs_token");location.reload()}else{list.innerHTML=`<p class="status error">${esc(err.message)}</p>`}}}
function render(){if(!games.length){list.innerHTML='<p class="empty">No games have been created.</p>';return}list.innerHTML=games.map(g=>`<article class="game ${g.is_open&&!g.signup_id?"":"closed"}"><div><h3>${esc(g.age_group)} — ${esc(g.field_name)}</h3><p class="meta">${fmtDate(g.game_date)} · ${fmtTime(g.start_time)} · ${g.duration_minutes} minutes</p><p><strong>${esc(g.location)}</strong></p>${g.signup_id?`<div class="signup-details"><strong>${esc(g.child_first)} ${esc(g.child_last)}, age ${g.child_age}</strong><br>Parent: ${esc(g.parent_first)} ${esc(g.parent_last)} · <a href="mailto:${esc(g.parent_email)}">${esc(g.parent_email)}</a> · ${esc(g.parent_phone)}${g.notes?`<br>Notes: ${esc(g.notes)}`:""}</div>`:`<p>${g.is_open?"Open — waiting for a referee":"Signup closed"}</p>`}</div><div class="actions"><button class="secondary edit" data-id="${g.id}">Edit</button>${g.signup_id?`<button class="danger remove-signup" data-id="${g.signup_id}">Remove Signup</button>`:""}<button class="danger delete" data-id="${g.id}">Delete Game</button></div></article>`).join("");list.querySelectorAll(".edit").forEach(b=>b.onclick=()=>openEdit(b.dataset.id));list.querySelectorAll(".delete").forEach(b=>b.onclick=()=>removeGame(b.dataset.id));list.querySelectorAll(".remove-signup").forEach(b=>b.onclick=()=>removeSignup(b.dataset.id))}
gameForm.onsubmit=async e=>{e.preventDefault();const b=gameForm.querySelector("button[type=submit]"),d=Object.fromEntries(new FormData(gameForm));b.disabled=true;try{await rpc("creator_add_games",{p_game_date:d.gameDate,p_start_time:d.startTime,p_duration_minutes:+d.duration,p_age_group:d.ageGroup.trim(),p_location:d.location.trim(),p_game_count:+d.gameCount,p_field_names:d.fields.trim(),p_public_notes:d.publicNotes.trim()},token);creatorStatus.className="status ok";creatorStatus.textContent="Referee openings created.";gameForm.reset();gameForm.duration.value=40;gameForm.gameCount.value=1;gameForm.ageGroup.value="U8";await load()}catch(err){creatorStatus.className="status error";creatorStatus.textContent=err.message}finally{b.disabled=false}};
function openEdit(id){const g=games.find(x=>x.id===id);for(const [k,v] of Object.entries({id:g.id,gameDate:g.game_date,startTime:String(g.start_time).slice(0,5),duration:g.duration_minutes,ageGroup:g.age_group,location:g.location,fieldName:g.field_name,publicNotes:g.public_notes||""}))editForm.elements[k].value=v;editForm.elements.isOpen.checked=g.is_open;editDialog.showModal()}
editDialog.querySelector(".close").onclick=()=>editDialog.close();editForm.onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(editForm));try{await rpc("creator_update_game",{p_id:d.id,p_game_date:d.gameDate,p_start_time:d.startTime,p_duration_minutes:+d.duration,p_age_group:d.ageGroup.trim(),p_location:d.location.trim(),p_field_name:d.fieldName.trim(),p_public_notes:d.publicNotes.trim(),p_is_open:!!d.isOpen},token);editDialog.close();await load()}catch(err){alert(err.message)}};
async function removeGame(id){if(!confirm("Delete this game and any signup attached to it?"))return;try{await rpc("creator_delete_game",{p_id:id},token);await load()}catch(err){alert(err.message)}}async function removeSignup(id){if(!confirm("Remove this referee signup and reopen the game?"))return;try{await rpc("creator_remove_signup",{p_signup_id:id},token);await load()}catch(err){alert(err.message)}}
document.querySelector("#download-report").onclick=()=>{const rows=games.filter(g=>g.signup_id).map(g=>({Date:g.game_date,"Start Time":fmtTime(g.start_time),"Length (Minutes)":g.duration_minutes,"Age Group":g.age_group,Location:g.location,Field:g.field_name,"Child First":g.child_first,"Child Last":g.child_last,Age:g.child_age,"Parent First":g.parent_first,"Parent Last":g.parent_last,"Parent Email":g.parent_email,"Parent Phone":g.parent_phone,Notes:g.notes||""}));if(!rows.length)return alert("There are no referee signups to report.");const ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Referees");XLSX.writeFile(wb,`cv-referee-report-${new Date().toISOString().slice(0,10)}.xlsx`)};
if(token)showCreator()})();
